version: '3.8'
services:
  postgres:
    image: postgres:16.1-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    tty: true
    profiles:
      - dev-integration
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      APP_DEBUG: '${APP_DEBUG:-false}'
      APP_URL: '${APP_URL:-http://localhost:9000}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD:-secret}'
      DB_HOST: '${DB_HOST:-postgres}'
    ports:
      - 9000:9000
    networks:
      - app-network
    depends_on:
      - postgres
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    restart: on-failure
    profiles:
      - dev-integration
    ports:
      - 9010:8080
    environment:
      SWAGGER_JSON: /docs/api-spec.yaml
    depends_on:
      - app
    volumes:
      - './docs:/docs'
    networks:
      - app-network
volumes:
  postgres-data:
    driver: local
networks:
  app-network:
    driver: bridge
